# Blog settings
permalink: /blog/:title

name: 'vlad.codes'
title: 'vlad.codes'
description: 'Vlad Shvedov - Software Development'
google_verification: null

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
